services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - conversion-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - conversion-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  conversion-api:
    build: ./conversion-api
    container_name: conversion-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - UPLOAD_DIR=/tmp/input
      - MONGODB_URI=mongodb://mongo:27017/converter
      - MONGO_URI=mongodb://mongo:27017/converter
      - REDIS_URL=redis://redis:6379
    volumes:
      - conversion-files:/tmp
      - ./conversion-api:/app
      - /app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - conversion-network

  conversion-worker-1:
    build: ./conversion-worker
    container_name: conversion-worker-1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/converter
    volumes:
      - conversion-files:/tmp
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      conversion-api:
        condition: service_started
    restart: unless-stopped
    networks:
      - conversion-network
  
  conversion-worker-2:
    build: ./conversion-worker
    container_name: conversion-worker-2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/converter
    volumes:
      - conversion-files:/tmp
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
      conversion-api:
        condition: service_started
    restart: unless-stopped
    networks:
      - conversion-network

volumes:
  mongo_data:
  conversion-files:

networks:
  conversion-network:
    driver: bridge